# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puma'
gem 'rest-client'
gem 'sinatra'
gem 'sinatra-cross_origin', '~> 0.3.1'

group :test do
  gem 'byebug'
  gem 'rack-test'
  gem 'rspec'
end
